spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mytask
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
